function Hd = band_pass_Equiripple (F_Pass1, F_Pass2, Sam_Freq, gain)
%BAND_PASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 17-Dec-2018 16:22:41

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = Sam_Freq;  % Sampling Frequency

N      = 20;   % Order
Fstop1 = F_Pass1 - 1;  % First Stopband Frequency
Fpass1 = F_Pass1;  % First Passband Frequency
Fpass2 = F_Pass2;  % Second Passband Frequency
Fstop2 = F_Pass2 + 1;  % Second Stopband Frequency
Wstop1 = 1;    % First Stopband Weight
Wpass  = 1;    % Passband Weight
Wstop2 = 1;    % Second Stopband Weight
dens   = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);
%fvtool(Hd);

% [EOF]
