function Hd = low_band_window (Sam_Freq, gain)
%LOW_BAND_WINDOW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 17-Dec-2018 16:34:03

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = Sam_Freq;  % Sampling Frequency

N    = 30;       % Order
Fc   = 170;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);
%fvtool(Hd);
% [EOF]
