function Hd = low_band_Equiripple (Sam_Freq)
%FIRST_BAND Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 17-Dec-2018 14:53:14

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = Sam_Freq;  % Sampling Frequency

N     = 20;   % Order
Fpass = 170;  % Passband Frequency
Fstop = 171;  % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 1;    % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);
%fvtool(Hd);

% [EOF]
